# Extracted to keep pipeline.py readable
FACILITY_MAP = {
    "NV-Banner Churchill Community Hospital":                        "32031",
    "NV-Battle Mountain General Hospital":                           "32005",
    "NV-Boulder City Hospital":                                      "32033",
    "NV-Carson Tahoe Emergent Care; Minden":                         "32140",
    "NV-Carson Tahoe Urgent Care; Carson Mall":                      "32141",
    "NV-Carson Tahoe Urgent Care; Dayton":                           "32143",
    "NV-Carson Valley Medical Center":                               "32057",
    "NV-Carson Valley Medical Center UC":                            "32147",
    "NV-Centennial Hills Hospital Medical Center":                   "32152",
    "NV-Desert View Regional Medical Center":                        "32066",
    "NV-Grover C. Dils Medical Center":                              "32060",
    "NV-Henderson Hospital":                                         "32153",
    "NV-Humboldt General Hospital":                                  "32058",
    "NV-Incline Village Community Hospital":                         "32160",
    "NV-Mesa View Regional Hospital":                                "32154",
    "NV-Mountain View Hospital":                                     "32017",
    "NV-Mt. Grant General Hospital":                                 "32155",
    "NV-North Vista Hospital":                                       "32156",
    "NV-Northeastern Nevada Regional Hospital":                      "32002",
    "NV-Northern Nevada Medical Center":                             "32022",
    "NV-Northern Nevada Sierra Medical Center":                      "32161",
    "NV-Pershing General Hospital":                                  "32061",
    "NV-Renown Regional Er":                                         "32024",
    "NV-Renown South Meadows Er":                                    "32064",
    "NV-Renown - North Carson UC":                                   "32136",
    "NV-Renown - Damonte Ranch UC":                                  "32121",
    "NV-Renown - Fallon UC":                                         "32126",
    "NV-Renown - Fernley UC":                                        "32127",
    "NV-Renown - Los Altos UC":                                      "32124",
    "NV-Renown - North HIlls UC":                                    "32122",
    "NV-Renown - Ryland UC":                                         "32119",
    "NV-Renown - Summit Ridge UC":                                   "32120",
    "NV-Renown - USA Pkwy UC":                                       "32131",
    "NV-Renown - Vista UC":                                          "32123",
    "NV-St. Mary's Regional Medical Center":                         "32025",
    "NV-South Lyon Medical Center":                                  "32059",
    "NV-Southern Hills Hosp & Med Ctr-Las Vegas":                    "32055",
    "NV-Spring Valley Hospital Medical Center":                      "32051",
    "NV-St. Rose Dominican Hospitals - Rose De Lima Campus":        "32157",
    "NV-St. Rose Dominican Hospitals - San Martin Campus":          "32158",
    "NV-St. Rose Dominican Hospitals - Siena Campus":               "32159",
    "NV-Summerlin Hospital Medical Center":                          "32018",
    "NV-Sunrise Hospital & Medical Center":                          "32013",
    "NV-UMCSN Blue Diamond Clinic":                                  "32139",
    "NV-UMCSN Centennial Primary Care":                              "32137",
    "NV-UMCSN Enterprise Quick Care":                                "32138",
    "NV-UMCSN Hospital Emergency Department-ER":                     "32142",
    "NV-UMCSN Nellis Primary Care":                                  "32144",
    "NV-UMCSN Peccole Primary Care":                                 "32145",
    "NV-UMCSN Rancho Primary Care":                                  "32146",
    "NV-UMCSN Southern Highlands Primary Care":                      "32148",
    "NV-UMCSN Spring Valley Primary Care":                           "32149",
    "NV-UMCSN Summerlin Primary Care":                               "32150",
    "NV-UMCSN Sunset Primary Care":                                  "32151",
    "NV-Valley Hospital Medical Center":                             "32011",
    "NV-William Bee Ririe Hospital":                                 "32039",
}